package.json, src/activate/registerCommands.ts, src/activate/registerTerminalActions.ts, src/core/CodeActionProvider.ts, src/core/webview/ClineProvider.ts, src/extension.ts
=> [WIP] fix: view id conflict

zgsm/src/common/env.ts
After the plugin is packaged, an extra / is added to the end of the baseurl.
Measures need to be taken to temporarily remove this additional / from the URL.
=> fix(config): read baseUrl error

src/activate/registerCommands.ts
=> feat: update right panel title to "ZHUGE SHENMA"

src/core/webview/ClineProvider.ts, src/core/webview/webviewMessageHandler.ts, src/exports/api.ts, src/extension.ts, zgsm/src/codeCompletion/completionCommands.ts
=> [WIP] fix: zgsm command id conflict

src/activate/handleUri.ts, src/auth/zgsmAuthHandler.ts
=> feat: add token callback

zgsm/src/common/services.ts, zgsm/src/i18n/locales/en/common.json, zgsm/src/i18n/locales/zh-CN/common.json
=> fix: status bar button issues

src/shared/storagePathManager.ts
=> fix: update customStoragePath from 'roo-cline' to 'features'

src/activate/registerCodeActions.ts, src/activate/registerCommands.ts, src/auth/zgsmAuthHandler.ts, src/shared/modes.ts, webview-ui/src/i18n/zgsm-setup.ts, webview-ui/src/i18n/zgsm_locales/en/settings.json, webview-ui/src/i18n/zgsm_locales/en/welcome.json, zgsm/src/chatView/chat-view-menu.ts, zgsm/src/codeCompletion/completionStatusBar.ts, zgsm/src/common/log-util.ts, zgsm/src/common/vscode-util.ts, zgsm/src/i18n/setup.ts
Updates all instances of 'ZGSM' to 'Shenma' in user prompts, logging, and translations to reflect the new branding.
Enhances user experience by providing consistent terminology across the codebase.
No functional changes implemented.
=> refactor: renames references from ZGSM to Shenma

src/api/providers/glama.ts, src/auth/zgsmAuthHandler.ts, src/integrations/theme/getTheme.ts, webview-ui/src/oauth/urls.ts
=> fix: update all references of 'rooveterinaryinc.roo-cline' to 'zgsm-ai.zgsm'

src/core/webview/ClineProvider.ts
Add logic in ClineProvider to track view movement state and ensure resources are only disposed when the view is actually closed. Introduce a timer to delay disposal, preventing accidental cleanup during view relocation between sidebars or panels.
=> fix: handle view movement and proper disposal

src/core/webview/ClineProvider.ts
=> fix: panel closed webview is disposed

src/integrations/terminal/TerminalRegistry.ts
=> refactor: rename new terminal

webview-ui/src/utils/validate.ts
Implements URL validation using the native URL constructor.
This change enhances reliability and simplifies the code by leveraging native browser functionality for URL validation.
1.validate success
2.validate error
=> fix: replaces URL validation logic with built-in method

src/api/providers/zgsm.ts
Adds `canParseURL` function to validate URLs safely Replaces direct usage of `URL.canParse` with the new utility
Improves code reliability and error handling
|   
|  
|
=> fix: Implements URL validation utility

src/shared/api.ts, webview-ui/src/components/settings/ApiOptions.tsx
=> feat: Add default ZGSM model configuration to API options

src/core/CodeActionProvider.ts
the image upload failed
before:
after:
=> fix: rename quick-fix

zgsm/src/codeCompletion/completionClient.ts, zgsm/src/i18n/locales/en/common.json, zgsm/src/i18n/locales/zh-CN/common.json, zgsm/src/i18n/locales/zh-TW/common.json
Adds a mechanism to prevent multiple error dialogs when login information retrieval fails. Introduces a prompt for users to re-login, enhancing user experience by guiding them to resolve authentication issues.
Updates localization files to include new error message for re-login.
=> fix: improves error handling for login failures

zgsm/src/codeCompletion/completionClient.ts, zgsm/src/common/services.ts
fix lint error, the `providerRef` in class `CompletionClient` is private
=> fix: lint error

src/activate/registerCodeActions.ts, zgsm/src/codeLens/codeLensCallBackFunc.ts
Remove the input hint box after click quick command or right menu
=> feat: remove input prompt after click quick command or right menu

zgsm/src/codeCompletion/completionTrace.ts
The completions.log should not exist in the production environment
=> refactor: remove unnecessary completions.log

src/api/providers/zgsm.ts, src/core/webview/webviewMessageHandler.ts, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, src/zgsmAuth/zgsmAuthHandler.ts, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/ModelPicker.tsx
Implements improved error handling in the ZGSM model retrieval process by returning detailed error information.
Adds an option to open a relogin prompt for 401 errors, enhancing user experience.
Updates related interfaces to accommodate new error handling structure.
Relates to user feedback on more informative error responses.
mock 401 scene
=> fix: enhances error handling for ZGSM model fetching

src/core/webview/webviewMessageHandler.ts
`https://www.abc.com/` to `https://www.abc.com`
=> feat: baseUrl format optimization

src/api/providers/zgsm.ts, src/core/webview/ClineProvider.ts, src/zgsmAuth/zgsmAuthHandler.ts, zgsm/src/codeCompletion/completionClient.ts
https://github.com/user-attachments/assets/d1fa55fa-d38f-4187-a349-2e4a7da44dee
=> fix: Default modelId missing

zgsm/src/codeCompletion/completionClient.ts
https://github.com/user-attachments/assets/6ad9344a-2b82-422d-8143-fc7b5c3aa6d1
=> fix: apiConfiguration is overwritten

src/extension.ts
automatically open sidebar to support new installation or upgrade
=> feat: automatically open sidebar to support new installation or upgrade

src/core/Cline.ts
=> feat: avoid the client repeatedly sending conversation requests to the llm.

src/core/webview/ClineProvider.ts, zgsm/src/codeCompletion/completionStatusBar.ts, zgsm/src/i18n/locales/en/common.json, zgsm/src/i18n/locales/zh-CN/common.json, zgsm/src/i18n/locales/zh-TW/common.json
Adds login method to ClineProvider to handle user authentication Updates CompletionStatusBar to reflect login status
=> fix: implements login functionality for ClineProvider

src/extension.ts
=> refactor: update output channel name from 'Roo-Code' to 'Shenma'

src/activate/registerTerminalActions.ts, src/api/providers/glama.ts, src/api/providers/human-relay.ts
merge files:
src/activate/registerTerminalActions.ts
src/api/providers/glama.ts
src/api/providers/human-relay.ts
=> feat:merge Roo Code conflicting code

.github/ISSUE_TEMPLATE/config.yml
=> fix the wrong feature request and review page URL

src/activate/registerCommands.ts, src/core/webview/ClineProvider.ts, src/exports/roo-code.d.ts, src/exports/types.ts, src/shared/ExtensionMessage.ts, webview-ui/src/components/chat/ChatRow.tsx, webview-ui/src/components/chat/ChatView.tsx
=> feat: merge Roo Code except confit code

src/schemas/index.ts, webview-ui/src/components/welcome/WelcomeView.tsx
=> feat: merge Roo Code

src/activate/handleUri.ts, src/core/config/ContextProxy.ts, src/core/webview/ClineProvider.ts, zgsm/src/codeCompletion/completionClient.ts, zgsm/src/codeCompletion/completionCommands.ts, zgsm/src/common/constant.ts, zgsm/src/common/services.ts, zgsm/src/extension.ts
Enhances user authentication by adding logic to manage authentication callbacks without opening the webview when a valid token is present.
Shenma has login but doesn't open webview
if token is expired
=> fix: user doesn't open webview but trigger completion

webview-ui/src/components/chat/Announcement.tsx, webview-ui/src/i18n/zgsm_locales/en/chat.json, webview-ui/src/i18n/zgsm_locales/en/welcome.json, webview-ui/src/i18n/zgsm_locales/zh-CN/chat.json, webview-ui/src/i18n/zgsm_locales/zh-CN/welcome.json, webview-ui/src/i18n/zgsm_locales/zh-TW/chat.json, webview-ui/src/i18n/zgsm_locales/zh-TW/welcome.json
=> fix: language bug fix

src/core/webview/webviewMessageHandler.ts, src/zgsmAuth/zgsmAuthHandler.ts, zgsm/src/codeCompletion/completionClient.ts, zgsm/src/common/services.ts
https://github.com/zgsm-ai/zgsm/issues/100
login page
setting page
=> fix: an infinite loop in login

src/activate/registerTerminalActions.ts, src/core/webview/ClineProvider.ts, src/schemas/index.ts
Closes: # no
The right menu don't work
before fixed:
https://github.com/user-attachments/assets/6d25d6b1-56c0-4497-88f3-5b67ace66e2e
after fixed:
=> fix: terminal menu

.gitignore, src/api/providers/zgsm.ts, src/core/task/Task.ts, src/core/webview/webviewMessageHandler.ts, src/integrations/terminal/__tests__/ExecaTerminal.spec.ts, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, webview-ui/src/components/chat/ChatView.tsx, webview-ui/src/components/chat/CommandExecutionError.tsx, webview-ui/src/components/prompts/PromptsView.tsx, webview-ui/src/components/settings/BrowserSettings.tsx, webview-ui/src/components/settings/CheckpointSettings.tsx, webview-ui/src/components/settings/SettingsView.tsx, webview-ui/src/components/settings/TerminalSettings.tsx, webview-ui/src/components/settings/__tests__/SettingsView.test.tsx, webview-ui/src/components/welcome/RooTips.tsx, webview-ui/src/components/welcome/WelcomeView.tsx, webview-ui/src/components/welcome/__tests__/RooTips.test.tsx, webview-ui/src/utils/validate.ts
Closes: # 
- Added docslink message handler in webview
- Updated error messages from "Shenme" to "Shenma"
- Modified documentation links to point to zgsm.ai
- Simplified settings save button behavior
-
- documentation links
[录屏 2025-05-26 23-03-12.webm](https://github.com/user-attachments/assets/f2eb73f5-6fac-4978-b0ba-2a1455a4e912)
- Simplified settings save button behavior
[录屏 2025-05-26 23-40-19.webm](https://github.com/user-attachments/assets/0717ee1d-30e9-4e89-977c-42732d21a933)
=> feat(webview): add docslink support and update error messages

package-lock.json, webview-ui/src/components/settings/About.tsx, webview-ui/src/components/ui/hooks/useSelectedModel.ts
Closes: # 
- Fix On-Premise model info
- Hide telemetry checkbox
=> fix: Fix On-Premise model info

src/extension.ts, webview-ui/index.html
Add logic to check if sidebar command is registered and reload window if needed. Stores reload state in global context to prevent infinite reload loops.
Closes: # 
[录屏 2025-06-03 01-06-22.webm](https://github.com/user-attachments/assets/e7659073-af81-4ddb-92e1-3cc1cfffe555)
=> feat(extension): add window reload check for command availability

package-lock.json, package.json
=> build: bump version from 1.4.0 to 1.4.1

.github/ISSUE_TEMPLATE/bug_report.yml
=> docs(issue-template): Rollback Bug Report Template

CHANGELOG.md
=> docs(changelog): update for versions 1.4.0 and 1.4.1

package-lock.json, package.json
=> build: update vscode engine requirement to ^1.86.2

src/core/task-persistence/taskMetadata.ts, src/core/task/Task.ts, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/AutoApproveSettings.tsx, webview-ui/src/components/settings/DiffSettingsControl.tsx, webview-ui/src/components/settings/NotificationSettings.tsx, webview-ui/src/components/settings/RateLimitSecondsControl.tsx, webview-ui/src/components/settings/SettingsView.tsx
feat(task): update zgsm provider and error handling improvements
- Add zgsm provider specific UI controls and conditional rendering
- Extract error handling logic into separate function with i18n support
- Add optional chaining for lastRelevantMessage.ts access
- Update settings submission to handle zgsm api key
Closes: # 
- export configuration comparison
- error handling improvements
before:
after:
=> feat: Update zgsm provider and error handling improvements

src/api/providers/zgsm.ts, src/core/task/Task.ts
=> feat(api): add task ID tracking and client identification headers

src/api/providers/lmstudio.ts, src/api/providers/mistral.ts, src/api/providers/vscode-lm.ts, src/core/task/Task.ts
=> fix(task): update error message to reflect correct model name

src/core/webview/ClineProvider.ts
Closes: # 
https://github.com/user-attachments/assets/6d6991fc-4534-4439-a6ab-0819347014c2
=> feat(webview): add clearHistory method for task history cleanup when reset extension

src/api/providers/zgsm.ts, src/core/task/Task.ts, src/core/webview/webviewMessageHandler.ts, webview-ui/src/components/chat/ChatView.tsx
Closes: # 
[录屏 2025-06-10 10-37-51.webm](https://github.com/user-attachments/assets/9331fd45-fc37-45f7-b041-9b454b8ec0da)
=> feat: Add chat type handling in ZgsmHandler and Task

src/api/providers/__tests__/openai.test.ts, src/api/providers/__tests__/openrouter.test.ts, src/api/providers/__tests__/requesty.test.ts, src/api/providers/constants.ts, src/api/transform/vscode-lm-format.ts, src/core/webview/ClineProvider.ts, src/integrations/terminal/BaseTerminal.ts, src/integrations/terminal/TerminalRegistry.ts, src/services/mcp/McpHub.ts
=> chore: update branding from Roo Code to Shenma

src/core/task/Task.ts, src/extension.ts, webview-ui/src/__tests__/ContextWindowProgress.test.tsx, webview-ui/src/components/chat/TaskHeader.tsx, webview-ui/src/components/chat/__tests__/TaskHeader.test.tsx
=> refactor(telemetry): Disable telemetry initialization and Context window UI and Enhance error logging 

src/core/config/ProviderSettingsManager.ts, src/core/webview/ClineProvider.ts, src/exports/roo-code.d.ts, src/exports/types.ts, src/schemas/index.ts, webview-ui/src/components/settings/SettingsView.tsx
=> feat: Add apikey update marker

CHANGELOG.md, package-lock.json, package.json
=> build: update version to 1.4.5

CHANGELOG.md, package-lock.json, package.json, webview-ui/src/components/settings/SettingsView.tsx
=> fix: resolve known issues and update to version 1.4.6

src/api/providers/zgsm.ts
=> feat(zgsm): update axios config and add timeout

src/core/webview/ClineProvider.ts, src/services/codeReview/api.ts, src/services/codeReview/codeReviewService.ts, zgsm/src/i18n/locales/en/common.json, zgsm/src/i18n/locales/zh-CN/common.json, zgsm/src/i18n/locales/zh-TW/common.json
=> feature: handle login logic

src/core/webview/ClineProvider.ts
=> fix(ClineProvider): fix the issue where the chat view is not opened when triggering codeAction

webview-ui/src/components/chat/ChatTextArea.tsx
=> feat: reduces minimum height of ChatTextArea for better UX

webview-ui/src/components/chat/ChatTextArea.tsx
=> feat: adds highlighting layer for mentions in chat textarea

CHANGELOG.md, package-lock.json, package.json
=> build: update version to 1.5.1

webview-ui/src/components/code-review/CodeReviewContent.tsx, webview-ui/src/i18n/zgsm_locales/en/codereview.json, webview-ui/src/i18n/zgsm_locales/zh-CN/codereview.json, webview-ui/src/i18n/zgsm_locales/zh-TW/codereview.json
=> feat(CodeReviewContent): add tooltip for filter button and update localization strings

src/api/providers/zgsm.ts, src/core/task/Task.ts, src/i18n/locales/en/apiErrors.json, src/i18n/locales/zh-CN/apiErrors.json, src/i18n/locales/zh-TW/apiErrors.json
=> chore: improve error handling and add new error case

src/services/codeReview/__tests__/codeReviewService.test.ts, src/services/codeReview/api.ts, src/services/codeReview/axiosInstance.ts, src/services/codeReview/codeReviewService.ts, src/services/codeReview/types.ts
=> feat: add cancel review task API and integrate it into CodeReviewService

README.md, README.zh-CN.md
=> docs: updates links in README files to full URLs

src/core/condense/index.ts, src/zgsmAuth/zgsmLoginManager.ts
=> fix: add error handling in summarizeConversation

CHANGELOG.md, package-lock.json, package.json
=> build: update to version 1.5.3

src/integrations/terminal/PowerShellCommandConverter.ts
=> refactor(PowerShellCommandConverter): Optimize argument conversion and remove redundant function

src/services/codeReview/codeReviewService.ts
=> feat(CodeReviewService): Add language information to the request header

CHANGELOG.md, package-lock.json, package.json
=> build: update to version 1.5.4

src/api/providers/zgsm.ts, src/core/codebase/client.ts, src/core/webview/ClineProvider.ts, src/services/codeReview/__tests__/codeReviewService.test.ts, src/services/codeReview/codeReviewService.ts, src/services/telemetry/PostHogClient.ts, src/utils/getClientId.ts, src/zgsmAuth/zgsmLoginManager.ts, zgsm/src/codeCompletion/completionClient.ts
Closes: # 
before:
after:
add independent suffix differentiation for each remote device
=> fix: remote device client_id value is incorrect

src/core/webview/ClineProvider.ts
=> refactor(ClineProvider): Optimize clearHistory method and reorder reset sequence

CHANGELOG.md, package-lock.json, package.json, src/shared/zgsmInitialize.ts
=> Update version 1.5.5

src/core/task/Task.ts, src/i18n/locales/en/apiErrors.json, src/i18n/locales/zh-CN/apiErrors.json, webview-ui/package-lock.json, webview-ui/package.json, webview-ui/src/components/common/MarkdownBlock.tsx, webview-ui/src/components/common/const.ts
=> feat: improves error handling and adds quota check messages

README.md, e2e/src/suite/index.ts, src/activate/registerCommands.ts, src/zgsmAuth/config.ts, webview-ui/src/components/chat/ChatTextArea.tsx, webview-ui/src/components/chat/ChatView.tsx, zgsm/src/common/env.ts
=> update: update zgsm.ai to costrict.ai

src/core/task/Task.ts, src/i18n/locales/en/apiErrors.json, src/i18n/locales/zh-CN/apiErrors.json
=> feat: improves error handling for quota and gateway issues

CHANGELOG.md, package-lock.json, package.json
=> build: Update to version 1.5.7

zgsm/src/codeCompletion/completionProvider.ts, zgsm/src/codeCompletion/completionTrace.ts, zgsm/src/common/constant.ts
=> refactor(completionTrace): enhance trace initialization and URL handling

src/core/mentions/index.ts, src/core/mentions/processUserContentMentions.ts, src/core/task/Task.ts, src/core/tools/readFileTool.ts, zgsm/src/core/tools/__tests__/readFileTool.test.ts, zgsm/src/core/tools/readFileTool.ts
=> feat(mentions): add file content truncation with task-aware limits

CHANGELOG.md, package-lock.json, package.json
=> build: Update to version 1.5.8 with optimizations and fixes

webview-ui/src/components/chat/AutoApproveMenu.tsx, webview-ui/src/components/chat/ChatTextArea.tsx, webview-ui/src/components/chat/EditModeControls.tsx
=> feat: merge roo v1

package.json, package.nls.json, package.nls.zh-CN.json, package.nls.zh-TW.json, src/core/tools/applyDiffTool.ts, src/core/tools/insertContentTool.ts, src/core/tools/searchAndReplaceTool.ts, src/core/tools/writeToFileTool.ts, src/utils/git.ts
=> feat: add AutoCommit feature to automatically commit changes after AI model modifications

src/api/index.ts, src/api/providers/zgsm.ts, src/api/transform/model-params.ts, src/core/task/Task.ts, src/zgsmAuth/zgsmAuthHandler.ts
=> refactor(optimize): optimize code and update ZgsmHandler for Grok and o4

src/core/tools/writeToFileTool.ts
=> fix(writeToFile): Fix the issue where the file writing tool calculates the number of changed lines in existing files incorrectly.

packages/types/src/vscode.ts, src/activate/registerCommands.ts, src/core/costrict/auth/authConfig.ts, src/extension.ts, src/package.json, src/package.nls.json, src/package.nls.zh-CN.json, src/package.nls.zh-TW.json, src/shared/ExtensionMessage.ts, webview-ui/src/components/chat/ChatView.tsx
=> adds new commands for user assistance and file context

zgsm/src/codeCompletion/completionProvider.ts
=> refactor(completion): remove feedback timer and related methods from AICompletionProvider

src/core/tools/applyDiffTool.ts, src/core/tools/insertContentTool.ts, src/core/tools/searchAndReplaceTool.ts, src/core/tools/writeToFileTool.ts
=> fix: add error handling for telemetry and auto-commit in multiple tools

CHANGELOG.md, package-lock.json, package.json
=> build: update to version 1.5.10

webview-ui/src/i18n/zgsm_locales/en/welcome.json, webview-ui/src/i18n/zgsm_locales/zh-CN/welcome.json, webview-ui/src/i18n/zgsm_locales/zh-TW/welcome.json
=> feat(i18n): update introduction text for English and Chinese locales in welcome.json

CHANGELOG.md, package-lock.json, package.json, src/api/providers/fetchers/unbound.ts, src/core/environment/getEnvironmentDetails.ts
=> build: Update to version 1.5.11 and refine error handling

package.json, src/activate/registerCommands.ts
=> feat: add new commands for context menu actions in editor and file explorer

e2e/src/suite/index.ts, src/api/providers/zgsm.ts, src/shared/api.ts, webview-ui/src/components/ui/hooks/useSelectedModel.ts
=> refactor(zgsm): update default model IDs to glm45-fp8

src/api/providers/zgsm.ts, src/core/task/Task.ts
=> feat: Optimize zgsm chat

CHANGELOG.md, package-lock.json, package.json
=> build: Update to version 1.5.12

packages/types/src/vscode.ts, src/activate/CodeActionProvider.ts, src/activate/registerCommands.ts, src/core/costrict/code-review/index.ts, src/core/webview/ClineProvider.ts, src/package.json, src/shared/support-prompt.ts, webview-ui/src/i18n/costrict-i18n/locales/en/welcome.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/welcome.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/welcome.json
=> feat: enhance code action capabilities and add new support prompts

src/core/costrict/code-review/__tests__/codeReviewService.spec.ts, src/core/costrict/code-review/codeReviewService.ts, src/core/costrict/code-review/index.ts, src/core/costrict/code-review/types.ts, src/core/costrict/codebase-index/client.ts, src/core/costrict/codebase-index/index.ts, src/core/costrict/codebase-index/types.ts, src/core/webview/webviewMessageHandler.ts, src/i18n/costrict-i18n/locales/en/common.json, src/i18n/costrict-i18n/locales/zh-CN/common.json, src/i18n/costrict-i18n/locales/zh-TW/common.json, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, src/shared/codeReview.ts, webview-ui/src/App.tsx, webview-ui/src/components/code-review/CodebaseSync.tsx, webview-ui/src/components/code-review/index.tsx, webview-ui/src/components/settings/ZgsmCodebaseSettings.tsx, webview-ui/src/context/ExtensionStateContext.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/codereview.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/codereview.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/codereview.json
=> feat: refactor codebase in codereview 

src/core/costrict/code-review/index.ts, webview-ui/src/components/code-review/CodeReviewContent.tsx, webview-ui/src/components/code-review/CodeReviewPanel.tsx, webview-ui/src/components/code-review/CodebaseSync.tsx, webview-ui/src/components/code-review/FileIssueList.tsx, webview-ui/src/components/code-review/IssueItem.tsx, webview-ui/src/components/code-review/TaskStatusBar.tsx, webview-ui/src/components/code-review/TaskSummary.tsx, webview-ui/src/components/code-review/contants.ts, webview-ui/src/components/code-review/index.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/codereview.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/codereview.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/codereview.json
=> feat: add review confidence filter

webview-ui/src/App.tsx
=> fix(App): update chat tab styling for improved layout and visibility

pnpm-lock.yaml, src/core/webview/webviewMessageHandler.ts, src/i18n/costrict-i18n/locales/en/common.json, src/i18n/costrict-i18n/locales/zh-CN/common.json, src/i18n/costrict-i18n/locales/zh-TW/common.json, src/package.json, src/shared/WebviewMessage.ts, webview-ui/src/components/chat/ChatRow.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/chat.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/chat.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/chat.json
=> feat: add copy error functionality and improve localization messages

src/api/providers/zgsm.ts
=> feat(zgsm): add logging for current model in streaming response

src/api/providers/zgsm.ts, src/core/costrict/error-code/ErrorCodeManager.ts, src/core/webview/webviewMessageHandler.ts
Closes: # 
- [] 🐛 **Bug Fix**: Non-breaking change that fixes an issue.
=> feat: modify the logic for obtaining error codes, add display of request ID.

src/i18n/index.ts
=> fix(i18n): import changeZgsmLanguage for language initialization and change functions

src/activate/registerCommands.ts
=> feat: updates panel icon paths to use SVG logos

src/core/costrict/code-review/codeReviewService.ts
=> feat: integrate default headers into CodeReviewService request options

webview-ui/src/components/settings/ModelPicker.tsx
Adds functionality to close the model picker dropdown when clicking outside of it or when a page message is received.
Utilizes `useLayoutEffect` to handle click events and manage dropdown state, improving user experience by ensuring the dropdown closes appropriately in different scenarios.
Closes: #
=> fix: Implements dropdown close behavior on outside click

CHANGELOG.md, src/package.json
=> build: Release version 1.6.1

src/package.json, src/package.nls.json, src/package.nls.zh-CN.json, src/package.nls.zh-TW.json, webview-ui/src/i18n/costrict-i18n/locales/en/account.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/account.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/account.json
=> feat: Update description

packages/types/src/mode.ts, src/core/costrict/activate.ts, src/shared/ExtensionMessage.ts, src/shared/__tests__/modes.spec.ts, webview-ui/src/App.tsx, webview-ui/src/components/chat/ReauthConfirmationDialog.tsx
=> feat: Update login tip

CHANGELOG.md, src/package.json
=> build: release version 1.6.2

src/core/costrict/codebase-index/index.ts, src/core/costrict/codebase-index/workspace-event-monitor.test.ts, src/core/costrict/codebase-index/workspace-event-monitor.ts
=> feat: add package info handling and improve file monitoring

src/core/costrict/activate.ts, src/i18n/costrict-i18n/locales/en/common.json, src/i18n/costrict-i18n/locales/zh-CN/common.json, src/i18n/costrict-i18n/locales/zh-TW/common.json
=> feat(i18n): enhance history cache warning with localization

CHANGELOG.md, src/package.json
=> build: update version to 1.6.3

src/api/providers/utils/response-render-config.ts, src/package.json
=> feat(response-render): add noLimit render mode option

CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, locales/zh-CN/CODE_OF_CONDUCT.md, locales/zh-CN/CONTRIBUTING.md, locales/zh-TW/CODE_OF_CONDUCT.md, locales/zh-TW/CONTRIBUTING.md
Replaces all instances of "Roo Code" with "Costrict" for consistency across documentation.
Changes email addresses for reporting issues to the project team, enhancing clarity for users.
Removes several language options in the Code of Conduct and Contributing files to streamline available translations.
Closes: #
=> fix: Updates project references and contact information

README.md, README.zh-CN.md, assets/docs/devel/en-US/deployment.md, assets/docs/devel/zh-CN/deployment.md
Replaces outdated links in the README files with new paths to the Deployment Guide for both English and Chinese versions.
Introduces a comprehensive deployment guide for the backend service, detailing system requirements, setup instructions, and configuration steps.
Removes the old development documentation files to streamline the repository.
Closes: #
=> feat: Updates deployment documentation and adds new guides

src/core/webview/ClineProvider.ts
=> fix(ClineProvider): update userName extraction from JWT to use displayName

src/utils/__tests__/shell.spec.ts, src/utils/shell.ts
Improves the mechanism for detecting PowerShell paths by implementing intelligent detection through the VS Code API and system checks.
Removes assumptions based on configuration and adds robust fallback options to ensure accurate shell detection across different platforms.
This change addresses inconsistencies in shell path resolution and enhances user experience by providing the correct shell based on the actual installed version.
Closes: # 
未设置默认shell（安装了pws7）
未配置默认shell（pws5.1）
=> feat: Enhances PowerShell detection logic in shell utilities

CHANGELOG.md, src/core/webview/webviewMessageHandler.ts, src/package.json, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/settings.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/settings.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/settings.json
=> Update version 1.6.6

webview-ui/src/components/settings/ProviderRenderer.tsx
Implements a message event listener to hide the select dropdown when an "action" type message is received.
Updates the select component to reflect its open state based on user interactions, enhancing the user experience by providing better control over the dropdown visibility.
Closes: #
=> feat: Adds message listener to control select visibility

src/utils/__tests__/shell.spec.ts, src/utils/shell.ts
Enhances the shell detection process by ensuring that the system's available shell is only detected if no previous shell is set. This change addresses potential issues where an undefined shell could lead to errors in subsequent operations.
Closes: #
=> feat: Improve shell detection logic for better reliability

CHANGELOG.md, src/package.json
=> build: release version 1.6.7

packages/types/src/provider-settings.ts, src/api/providers/zgsm.ts, src/core/costrict/codebase-index/git-checkout-detector.ts, src/core/task/Task.ts, webview-ui/src/components/common/HighlightedPlainText.tsx, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/RateLimitSecondsControl.tsx, webview-ui/src/components/settings/providers/ZgsmAI.tsx, webview-ui/src/components/ui/hooks/useSelectedModel.ts
=> refactor(zgsm): rename openAiCustomModelInfo to zgsmAiCustomModelInfo and improve rate limiting

CHANGELOG.md, src/package.json
=> build: version bump to 1.6.10

webview-ui/src/components/settings/ProviderRenderer.tsx
=> style: update conditional class for provider renderer visibility

packages/telemetry/src/prometheus/MetricsSerializer.ts, packages/telemetry/src/prometheus/PrometheusTelemetryClient.ts
=> fix(telemetry): enhance metrics loading and pushing logic in PrometheusTelemetryClient

webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/providers/ZgsmAI.tsx
Implements a button to refresh router models in the ZgsmAI component.
The button triggers a refetch of router models and provides user feedback upon success.
This enhancement improves the user experience by allowing dynamic updates of models without needing to reload the component.
Closes: # 
// clear cache file
// click fresh button
// cache file rewrite
=> feat: Adds refresh functionality for router models in ZgsmAI

webview-ui/src/components/chat/ChatRow.tsx, webview-ui/src/components/chat/ChatTextArea.tsx, webview-ui/src/components/settings/providers/ZgsmAI.tsx, webview-ui/src/utils/path-mentions.ts
=> feat: add line navigation for file jumps in chat interface

CHANGELOG.md, src/package.json
=> build: Update version to 1.6.11

src/api/providers/zgsm.ts
=> feat: add logging for request and response IDs in ZgsmAiHandler

src/core/webview/webviewMessageHandler.ts
Updates the webview message handler to use default values from the API configuration for `baseUrl` and `apiKey` if they are not provided in the message.
This change enhances flexibility and ensures that the application can function correctly even when specific values are not supplied.
Closes: # 
// click refresh model
// Intranet
// after refresh model
=> fix: Improve default values for zgsm configuration

CHANGELOG.md, packages/types/src/providers/zgsm.ts, src/package.json
=> build: update version to 1.6.12

src/i18n/costrict-i18n/locales/en/common.json, src/i18n/costrict-i18n/locales/zh-CN/common.json, src/i18n/costrict-i18n/locales/zh-TW/common.json
Updates localization strings for the function quick menu and code completion features to enhance clarity and consistency across English, Simplified Chinese, and Traditional Chinese locales.
Removes unnecessary qualifiers such as "Intelligent" and "Function," simplifying the language for a better user experience.
Closes: # 
// zh-cn
// zh-tw
// en-us
=> feat: Refines localization strings for clarity

packages/types/src/global-settings.ts, src/core/mentions/index.ts, src/core/mentions/processUserContentMentions.ts, src/core/task/Task.ts, src/core/webview/ClineProvider.ts, src/core/webview/webviewMessageHandler.ts, src/integrations/misc/__tests__/extract-text.spec.ts, src/integrations/misc/extract-text.ts, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, webview-ui/src/components/settings/ContextManagementSettings.tsx, webview-ui/src/components/settings/SettingsView.tsx, webview-ui/src/context/ExtensionStateContext.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/settings.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/settings.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/settings.json
=> feat: add file read character limit

webview-ui/src/components/chat/ChatRow.tsx, webview-ui/src/i18n/costrict-i18n/locales/en/prompts.json, webview-ui/src/i18n/costrict-i18n/locales/zh-CN/prompts.json, webview-ui/src/i18n/costrict-i18n/locales/zh-TW/prompts.json
=> Workflow test2

CHANGELOG.md
=> build: update version to 1.6.13

CHANGELOG.md, src/package.json
=> build: version 1.6.15

webview-ui/src/components/cloud/ZgsmAccountView.tsx
=> fix: handle null quota display in ZgsmAccountView

src/core/costrict/code-review/__tests__/codeReviewService.spec.ts, src/core/costrict/code-review/codeReviewService.ts, src/core/costrict/code-review/types.ts, src/shared/codeReview.ts, webview-ui/src/components/code-review/CodeReviewContent.tsx, webview-ui/src/components/code-review/CodeReviewPanel.tsx, webview-ui/src/components/code-review/CodebaseSync.tsx, webview-ui/src/components/code-review/TaskStatusBar.tsx, webview-ui/src/components/code-review/index.tsx
=> feat: enhance the progress visualization in the code review service.

CHANGELOG.md, src/core/task/Task.ts, src/package.json, webview-ui/src/components/chat/ChatRow.tsx
=> build: version 1.6.17

src/api/providers/utils/openai-error-handler.ts, src/core/task/__tests__/Task.spec.ts
=> fix: preserve original status in error handling for OpenAI client

webview-ui/src/components/cloud/ZgsmAccountView.tsx, webview-ui/src/hooks/useZgsmUserInfo.ts
=> feat(cloud): add user ID display and improve avatar handling
